server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aioceaneye_db
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    table: flyway_client_migrations
    baseline-version: 0
    baseline-on-migrate: true

cloud:
  aws:
    image-bucket:
      name: "information-images"
      folders:
        companies: "companies"
        vessels: "vessels"
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "clients"
    description: "Clients (Company & Ship) Application in AiOceanEye"
    version: "1.0.0"
