server:
  port: 8050

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aioceaneye_db
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: drone_service
    show-sql: true
  flyway:
    schemas: drone_service
    table: flyway_drone_migrations
    sql-migration-prefix: DV_
    baseline-version: '1'
    baseline-on-migrate: true
    locations: classpath:db/migration/drone

cloud:
  aws:
    image-bucket:
      name: "information-images"
      folders:
        drones: "drones"
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "drones"
    description: "Drones Application in AiOceanEye"
    version: "1.0.0"
