server:
  port: 8050

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aioceaneye_db
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

cloud:
  aws:
    image-bucket:
      name: "information-images"
      folders:
        drones: "drones"
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "drones"
    description: "Drones Application in AiOceanEye"
    version: "1.0.0"
