server:
  port: 8060

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aoe_materials_db?characterEncoding=UTF-8&useUnicode=yes&connectionCollation=utf8mb4_unicode_ci
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection:
          charSet: utf8mb4
          characterEncoding: utf8mb4
          useUnicode: yes
  flyway:
    table: flyway_material_migrations
    baseline-version: 0
    baseline-on-migrate: true
    
cloud:
  aws:
    image-bucket:
      name: "information-images"
      folders:
        materials: "materials"
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "materials"
    description: "Materials Application in AiOceanEye"
    version: "1.0.0"
